checks:
  - name: "single-nested-if"
    code: "SNI"
    id: "CL001"
    description: "Ensure the presence of single nested 'if' statements within function bodies."
    pattern: './/FunctionDef/body//If'
    count:
      min: 1
      max: 10

  - name: "double-nested-if"
    code: "DNI"
    id: "CL002"
    description: "Ensure the presence of double nested 'if' statements within function bodies."
    pattern: './/FunctionDef/body//If[ancestor::If and not(parent::orelse)]'
    count:
      min: 1
      max: 10

  - name: "explicit-return-in-init"
    code: "RET"
    id: "RET001"
    description: "Using an explicit return statement in the __init__ function"
    pattern: './/FunctionDef[@name="__init__"]/body/Return'
    count:
      min: 1
      max: 10

  - name: "none-comparison"
    code: "NONE"
    id: "NONE001"
    description: "Using != None to check for non-None values"
    pattern: './/FunctionDef//Compare/left[@id="input_dirs"]/following-sibling::Compare/ops/NotEq | .//FunctionDef//Compare/comparators[@id="input_dirs"]/following-sibling::Compare/ops/NotEq'
    count:
      min: 1
      max: 10

  - name: "no-exception-type"
    code: "EXC"
    id: "EXC001"
    description: "No exception type(s)"
    pattern: './/FunctionDef//Try/ExceptHandler[not(ExceptHandler/type)]'
    count:
      min: 1
      max: 10

  - name: "boolean-comparison"
    code: "BOOL"
    id: "BOOL001"
    description: "Using = or == operators to compare boolean values"
    pattern: './/FunctionDef//Compare/ops/Is | .//FunctionDef//Compare/ops/Eq'
    count:
      min: 1
      max: 10

  - name: "missing-annotations"
    code: "ANNOT"
    id: "ANNOT001"
    description: "A function does not explicitly annotate arguments/parameters or the expected output"
    pattern: './/FunctionDef[not(args/arg/annotation) or not(returns)]'
    count:
      min: 1
      max: 10

  - name: "key-function"
    code: "KFUN"
    id: "KF001"
    description: "The use of .keys() function"
    pattern: './/FunctionDef//Call/func/Attribute[@attr="keys"]'
    count:
      min: 1
      max: 10

  - name: "multi-value-key-literal"
    code: "MVKL"
    id: "MVKL001"
    description: "Looks to see if a key has been repeated"
    pattern: './/FunctionDef/body/Assign/value/Dict/keys/Name[preceding-sibling::Name/@id = @id]'
    count:
      min: 1
      max: 10

  - name: "assert-tuple"
    code: "AT"
    id: "AT001"
    description: "Looks to see if assert is used on a tuple"
    pattern: './/FunctionDef[./body/Assert/test/Tuple]'
    count:
      min: 1
      max: 10

  - name: "loop-variable-iterates-overrides-iterator"
    code: "LVITOI"
    id: "LVITOI001"
    description: "If the iterator has the same name as the things it's iterating through"
    pattern: './/FunctionDef/body/For[target/Name/@id = iter/Name/@id]'
    count:
      min: 1
      max: 10

  - name: "function-uses-loop-variable"
    code: "FLV"
    id: "FLV001"
    description: "The loop variable is not bound in the function definition, so it will always have the value it had in the last iteration"
    pattern: './/FunctionDef[body//comprehension/target/Name]'
    count:
      min: 1
      max: 10

  - name: "nested-depth"
    code: "ND"
    id: "F001"
    description: "Ensure the depth of nesting within functions does not exceed the set value."
    pattern: './/FunctionDef//FunctionDef/ancestor::*'
    count:
      min: 1
      max: 10

  - name: "number-of-conditions-in-function"
    code: "#Cond"
    id: "F002"
    description: "Ensure the number of conditions (if, if-else, and switch) in a function is within acceptable limits."
    pattern: './/FunctionDef//If/following-sibling::If | .//FunctionDef//If/following-sibling::Elif | .//FunctionDef//If/following-sibling::Else'
    count:
      min: 1
      max: 10

  - name: "nested-conditions"
    code: "IFIF"
    id: "CL001"
    description: "Ensure there is at least one nested condition (e.g., if{if{}}) in a function."
    pattern: './/FunctionDef//If/descendant::If'
    count:
      min: 1
      max: 1

  - name: "nested-condition-loops"
    code: "IFOR"
    id: "CL002"
    description: "Ensure the presence of nested condition-loops (e.g., if{for{}}) in a function."
    pattern: './/FunctionDef//if//For'
    count:
      min: 1
      max: 10

  - name: "nested-loop-conditions"
    code: "VFF"
    id: "C002"
    description: "Ensure the presence of nested loop-conditions (e.g., for{if{}}) in a function."
    pattern: './/FunctionDef[//(If/following-sibling::For | For/following-sibling::If)]'
    count:
      min: 1
      max: 10

  - name: "nested-loop-conditions-ff"
    code: "FF"
    id: "F001"
    description: "Ensure the presence of nested loop-conditions (e.g., for{for{}}) in a function."
    pattern: './/FunctionDef//For[.//For]'
    count:
      min: 1
      max: 10

  - name: "number-of-assertions"
    code: "NOA"
    id: "NOA001"
    description: "Ensure the presence of assertions within function bodies."
    pattern: './/FunctionDef/body/Assert'
    count:
      min: 1
      max: 10

  - name: "count-test-method-lines"
    code: "LOF"
    id: "LOF001"
    description: "Count the lines within test methods that start with 'test_'."
    pattern: './/FunctionDef[starts-with(@name, "test_")]/body/*'
    count:
      min: 1
      max: 10

  - name: "count-method-lines"
    code: "CML"
    id: "CML001"
    description: "Count the lines within methods."
    pattern: './/FunctionDef/body/* | .//FunctionDef/body/Return'
    count:
      min: 1
      max: 10

  - name: "test-methods-invoking-method"
    code: "TMIM"
    id: "TMIM001"
    description: "Identify test methods invoking specific methods."
    pattern: './/FunctionDef[starts-with(@name, "test_")]//Assert[count(.//Call[func/Name/@id="test_function"]) > 0]'
    count:
      min: 1
      max: 10

  - name: "not-using-context-manager"
    code: "DUCM"
    id: "DUCM001"
    description: "Detect file handling without using the context manager."
    pattern: './/FunctionDef//*[starts-with(., "with open")]'
    count:
      min: 1
      max: 10

  - name: "multiple-returns-in-function"
    code: "MRET"
    id: "MRET001"
    description: "Detect functions with multiple return statements."
    pattern: './/FunctionDef[count(body//Return) > 2]'
    count:
      min: 1
      max: 10

  - name: "complex-expressions"
    code: "COMPLEX"
    id: "COMPLEX001"
    description: "Detect complex expressions with multiple operators."
    pattern: './/FunctionDef//BinOp[count(descendant::BinOp) > 2]'
    count:
      min: 1
      max: 10

  - name: "unused-variables"
    code: "UNUSED"
    id: "UNUSED001"
    description: "Detect variables that are defined but not used."
    pattern: '//FunctionDef[starts-with(@name, "test_")]//Assert[count(.//Call[func/Name]) > 0]'

  