"""Program to execute and store Chasten and Mutmut analysis for lazytracker"""

import typer
import subprocess

# Resource: https://docs.python.org/3/library/subprocess.html
import json
import os
from glob import glob
from contextlib import chdir
from rich.console import Console
from pathlib import Path
from json_restruct import json_restruct
from add_function_json import add_function_to_json

cli = typer.Typer()

def install_package(package):
    """Install the specified Python package using pip."""
    subprocess.run(["pipx", "install", package])


def check_installation(package) -> bool:
    """Check if the specified Python package is installed."""
    try:
        subprocess.run(
            [package, "--version"],
            stdout=subprocess.PIPE,
            stderr=subprocess.PIPE,
            check=True,
        )
        # I learned to use a PIPE with the subprocess module here: https://stackoverflow.com/questions/13332268/how-to-use-subprocess-command-with-pipes
    except subprocess.CalledProcessError or FileNotFoundError:
        #  The package isn't installed, then return false: https://stackoverflow.com/questions/32942207/python-subprocess-calledprocesserror-command-returned-non-zero-exit-s
        return False
    return True


def execute_chasten(search_path, save_directory, chasten_config_path):
    """Execute the chasten analyze command for lazytracker."""
    # Resource: https://github.com/AstuteSource/chasten/tree/chastenversion

    chasten_command = [
        "chasten",
        "analyze",
        "lazytracker",
        "--config",
        chasten_config_path,
        "--search-path",
        str(search_path),
        "--save-directory",
        str(save_directory),
        "--save",
    ]
    subprocess.run(chasten_command)
    json_files = glob("*.json")
    if not json_files:
        raise FileNotFoundError("No JSON files generated by chasten command")
    json_name = max(json_files, key=os.path.getctime)
    with open(json_name) as f:
        file = json.load(f)
    os.remove(json_name)
    return file


def calculate_score(chasten_result, custom_scores):
    total_score = 0
    total_checks_detected = 0

    for source in chasten_result['sources']:
        check = source['check']
        check_id = check['id']
        matches = check['matches']
        total_matches = len(matches)
        
        # Lookup custom score for the check ID
        check_score = custom_scores.get(check_id, 0)  # Default score is 0 if not specified
        
        total_score += check_score
        if total_matches > 0:
            total_checks_detected += 1

    if total_checks_detected == 0:
        return 0  # Avoid division by zero

    average_score = total_score / total_checks_detected
    return average_score


def save_results(chasten_result, save_file):
    """Save chasten and mutmut results in a JSON file"""
    result = {"chasten_result": chasten_result}
    with open(save_file, "w") as f:
        json.dump(result, f, indent=2)
        # Need a custom pretty-print, so I learned from this resource: https://stackoverflow.com/questions/63949556/how-to-custom-indent-json-dump


@cli.command()
def analyzer(
    search_path: Path = os.getcwd() + "/demo/lazytracker",
    save_directory: Path = os.path.abspath(os.path.dirname(__file__)),
    chasten_config_path: str = os.getcwd() + "/Config",
):
    """Runs chasten and mutmut, consolidates the data into a json."""
    console = Console()
    # Step 1: Check and install chasten and mutmut if not installed
    # Save in the script's directory default
    custom_weights = {
        "C001": 0,
        "F001": 0.33049242424242414,
        "F002": 0.29820936639118445,
        "CL001": 0.22424242424242422,
        "CL002": 0,
        "IMP001": 0,
        "RET001": 0,
        "NONE001": 0,
        "EXC001": 0,
        "BOOL001": 0.21212121212121213,
        "ANNOT001": 0.36994949494949486,
        "KFUN001": 0,
        "MVKL001": 0,
        "AT001": 0,
        "LVITOI001": 0,
        "FLV001": 0.21212121212121213,
        "ND001": 0,
        "FC002": 0,
        "IFIF001": 0,
        "IFOR001": 0,
        "VFF001": 0,
        "FF001": 0,
        "NOA001": 0,
        "LOF001": 0,
        "CML001": 0.33021390374331544,
        "TMIM001": 0,
        "DUCM001": 0,
        "IF001": 0,
        "F406": 0,
        "F632": 0,
        "F701": 0
    }


    if not check_installation("chasten"):
        install_package("chasten")

        # Step 2: Execute chasten and save the result
        chasten_result = execute_chasten(
            search_path, save_directory, chasten_config_path
        )

        # Calculate the score
        score = calculate_score(chasten_result, custom_weights)
        console.print(f"Predicted Score: {score}")

        # Step 3: Run mutmut and save its result
        # Step 4: Save results in a file
        save_results(chasten_result, "alish_result.json")
        console.print("\n\nCode analysis and mutation prediction complete!")
        console.print("Result is stored in file named alish_result.json")
